### ISSUE TITLE
Exit preview response is hanging

### ISSUE THREAD

**Issue by codeKenta** [SimeonGriggs/sanity-nextjs-preview#2]
When routing to `api/exit-preview`, the response is hanging. It's probably solved by adding res.end()

**Comment by SimeonGriggs** [comment]
Good call, fixed in [d1d01ae](https://github.com/SimeonGriggs/sanity-nextjs-preview/commit/d1d01ae08071ef7c63498412b8fcb9cfa4a0d97f)
